### ISSUE TITLE
seg fault?

### ISSUE THREAD

**Issue by alexmyczko** [insanum/minichess#2]
$ minichess
gnuchess: invalid option -- 'T'
gnuchess: invalid option -- 'C'
Segmentation fault (core dumped)

what version of gnuchess was that, some years ago?

**Comment by insanum** [comment]
Not sure. Over 15yrs ago. :-)

**Comment by alexmyczko** [comment]
Heh. Well the options -T and -C to gnuchessx are not recognized anymore. And running it in ltrace/strace gives also a big more detail. Also, it leaves child processes using CPU (the gnuchessx calls). Do you still play chess? Maybe we play a few times, the losing party has to fix minichess...
